#!/bin/bash
# Fast computational sensors. Every check exists because that exact failure
# actually happened once. Add a check whenever a mistake recurs.
set -uo pipefail
cd "$(dirname "$0")/.."
SRC="LockIn Set Tracker"
FAIL=0

FAILED_COUNT=0
pass() { echo "  PASS  $1"; }
fail() { echo "  FAIL  $1"; FAIL=1; FAILED_COUNT=$((FAILED_COUNT+1)); }

echo "== Lokt harness checks =="

# 1. Banned visual styles (the "AI slop" list — restyle commits c6a9680/2489105).
#    Blue/purple accents and AngularGradient are banned EVERYWHERE.
BANNED=$(grep -rnE '0\.29, *0\.62, *1\.00|0\.56, *0\.53, *0\.96|Color\.blue|#2A5285|#4A9EFF|AngularGradient' \
  --include="*.swift" "$SRC" | grep -v "^Binary")
if [ -n "$BANNED" ]; then fail "banned style (blue/purple/angular gradient) found:"; echo "$BANNED" | head -5
else pass "no banned styles (blue/purple, angular gradients)"; fi

# 1b. Depth stays in the token layer (v2 look, phase 1). Linear/radial
#     gradients and `.shadow(` are allowed ONLY in Theme.swift — home of
#     `AppTheme.primaryGradient`, `.primaryGlow()`, `AppTheme.cardHighlight` and
#     `.heroGlow()`. Every view reaches depth through those tokens; a gradient
#     or shadow written in a view file is the old AI-slop failure in new clothes.
DEPTH=$(grep -rnE 'LinearGradient|RadialGradient|\.shadow\(' \
  --include="*.swift" "$SRC" | grep -v "^Binary" | grep -v "^$SRC/Theme.swift:")
if [ -n "$DEPTH" ]; then fail "gradient/shadow outside Theme.swift (use AppTheme.primaryGradient / .primaryGlow() / .heroGlow() / cardHighlight):"; echo "$DEPTH" | head -5
else pass "gradients/shadows live only in Theme.swift (views use the depth tokens)"; fi

# 1c. Per-scheme pill-gradient stops: every AccentScheme carries a light/dark
#     pair ordered light > base > dark in luminance, the near-black label clears
#     4.5:1 on the dark stop, and ice's glow stays subtle. Extracted from the
#     REAL Theme.swift (Python: it imports UIKit, so no macOS swiftc harness);
#     prints its own PASS/FAIL lines.
if ! python3 harness/logic-checks/accent-gradient-stops/check.py; then FAIL=1; FAILED_COUNT=$((FAILED_COUNT+1)); fi

# 2. Color literals outside the token layer (Theme.swift is the only home).
LITERALS=$(grep -rn 'Color(red:' --include="*.swift" "$SRC" | grep -v "Theme.swift")
if [ -n "$LITERALS" ]; then fail "Color(red:) literal outside Theme.swift:"; echo "$LITERALS" | head -5
else pass "all color literals live in Theme.swift"; fi

# 3. exercises.json must be valid JSON (a 1-char corruption once nearly shipped —
#    it would have silently emptied the entire 1k+-exercise library).
if python3 -c "import json;json.load(open('$SRC/exercises.json'))" 2>/dev/null
then pass "exercises.json is valid JSON"
else fail "exercises.json is INVALID JSON — the exercise library would load empty"; fi

# 3b. Deep dataset lint (schema, decoder enums, unique ids/names, content floor).
#     Added with the researched dataset expansion; prints its own PASS/FAIL line.
#     Duplicate names that predate the lint are grandfathered inside the script.
if ! python3 harness/dataset-lint.py; then FAIL=1; FAILED_COUNT=$((FAILED_COUNT+1)); fi

# 3c. Backend exercise catalog must not drift from the dataset. The AI backend
#     grounds generated exercise names in backend/exercise-catalog.json
#     (generated by harness/gen-exercise-catalog.py from exercises.json +
#     ExerciseAliases.swift); a stale committed catalog would silently feed the
#     model outdated names.
TMP_CATALOG=$(mktemp)
if python3 harness/gen-exercise-catalog.py --out "$TMP_CATALOG" >/dev/null 2>&1 \
   && cmp -s "$TMP_CATALOG" backend/exercise-catalog.json
then pass "backend/exercise-catalog.json matches dataset (no drift)"
else fail "backend/exercise-catalog.json is stale — regenerate: python3 harness/gen-exercise-catalog.py"; fi
rm -f "$TMP_CATALOG"

# 3d. Backend sanitize/post-check logic (persona 2026-09-01 NEW-1: the dupe-
#     dropper destroyed percent-based programming). Pure-node assertions
#     extracted from the real server.mjs — zero OpenAI cost, prints its own
#     PASS/FAIL lines.
if ! node harness/logic-checks/backend-sanitize-merge/check.mjs; then FAIL=1; FAILED_COUNT=$((FAILED_COUNT+1)); fi

# 3e. Coach multi-draft path (owner ask 2026-09-23: "one at a time is the
#     default, but at least two if the person asks"). Count cap, duplicate
#     drop, same sanitize pipeline per draft, single-draft shape unchanged,
#     safety-branch contexts stay single. Extracted from the real server.mjs.
if ! node harness/logic-checks/backend-coach-multi-draft/check.mjs; then FAIL=1; FAILED_COUNT=$((FAILED_COUNT+1)); fi

# 4. Exactly one ExerciseStore() construction (app root). Per-view copies each
#    re-decoded 2MB of JSON (fixed in f4d6798).
COUNT=$(grep -rn "ExerciseStore()" --include="*.swift" "$SRC" | wc -l | tr -d ' ')
if [ "$COUNT" = "1" ]; then pass "single shared ExerciseStore (1 construction)"
else fail "expected exactly 1 ExerciseStore() construction, found $COUNT"; fi

# 5. No API keys in tracked sources (defense in depth; .env is gitignored).
KEYS=$(grep -rnE 'sk-[A-Za-z0-9_-]{20,}' --include="*.swift" --include="*.mjs" --include="*.json" "$SRC" backend/server.mjs 2>/dev/null)
if [ -n "$KEYS" ]; then fail "possible API key committed in sources:"; echo "$KEYS" | head -3
else pass "no API keys in sources"; fi

# 6. M1b ownership gate: only WorkoutStore may access the legacy persistence
#    keys for routines and sessions.
DIRECT=$(grep -rnE 'forKey: *"(routines|workoutSessions)"' --include="*.swift" "$SRC" | grep -v "WorkoutStore.swift" | wc -l | tr -d ' ')
if [ "$DIRECT" = "0" ]; then pass "WorkoutStore exclusively owns routines/workoutSessions persistence"
else fail "found $DIRECT direct 'routines'/'workoutSessions' accesses outside WorkoutStore"; fi

# 7. TestFlight always uses the shipped backend. A user-editable server URL or
# localhost fallback lets a stale development setting strand a beta build.
BACKEND_ESCAPE=$(grep -rnE 'aiBackendBaseURL|AIBackendSettingsView|fallbackLocalBaseURLStrings|persistWorkingBaseURL|127\.0\.0\.1|localhost' --include="*.swift" "$SRC")
if [ -n "$BACKEND_ESCAPE" ]; then fail "TestFlight backend override/fallback found:"; echo "$BACKEND_ESCAPE" | head -5
else pass "TestFlight backend is fixed to the shipped Railway URL"; fi

# 8. Coach response chrome must have a real action, not decorative social
# icons left over from the chat mockup.
COACH_PLACEHOLDERS=$(grep -nF 'ForEach(["doc.on.doc", "hand.thumbsup", "hand.thumbsdown", "square.and.arrow.up", "ellipsis"]' "$SRC/CoachView.swift")
if [ -n "$COACH_PLACEHOLDERS" ]; then fail "Coach placeholder action row found"
else pass "Coach response actions are functional"; fi

# 9. Screenshot staging must never ship into a TestFlight build.
STAGING=$(grep -rn 'LOKT_STAGE' --include="*.swift" "$SRC")
if [ -n "$STAGING" ]; then fail "temporary screenshot staging found:"; echo "$STAGING" | head -5
else pass "no temporary screenshot staging"; fi

# 10. `PrimaryButtonStyle(prominence: .ai)` — the gradient + glow pill — is
#     reserved for AI entry points (owner feedback build 4: "you tried too
#     hard adding the colors"; the neon should help, not take over). Every
#     other primary action is the flat `.standard` capsule. The allow-list
#     mirrors CLAUDE.md → Design system → "Button prominence"; add a file
#     there AND here when a new AI entry point ships.
AI_ALLOWED=" AIWorkoutGeneratorView.swift CoachView.swift CreateWorkoutOptionsView.swift ExerciseSwapService.swift SupplementaryWorkoutGeneratorView.swift VoiceWorkoutImportView.swift WorkoutPhotoImportView.swift WorkoutTabView.swift "
AI_STRAY=""
while IFS= read -r f; do
  [ -z "$f" ] && continue
  b=$(basename "$f")
  case "$AI_ALLOWED" in *" $b "*) ;; *) AI_STRAY="$AI_STRAY $b";; esac
done <<< "$(grep -rlE 'prominence: *\.ai' --include="*.swift" "$SRC")"
if [ -n "$AI_STRAY" ]; then fail "prominence: .ai outside the AI entry-point views (see CLAUDE.md allow-list):$AI_STRAY"
else pass "prominence: .ai only on AI entry-point views"; fi

echo "=========================="
if [ $FAIL -eq 0 ]; then echo "ALL CHECKS PASSED"; else echo "CHECKS FAILED"; fi

# Append to local run history (gitignored) — fuels harness/dashboard.sh.
PASSBOOL=$([ $FAIL -eq 0 ] && echo true || echo false)
echo "{\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"kind\":\"checks\",\"pass\":$PASSBOOL,\"m1b\":$DIRECT,\"failedCount\":$FAILED_COUNT}" >> harness/history.jsonl

exit $FAIL
